version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tic-tac-claude-db
    environment:
      POSTGRES_DB: tictactoe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tic-tac-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tic-tac-claude-backend
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tictactoe
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - tic-tac-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tic-tac-claude-frontend
    environment:
      - VITE_API_URL=http://localhost:3000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - tic-tac-network

volumes:
  postgres_data:

networks:
  tic-tac-network:
    driver: bridge